[package]
name = "flight-app"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
chrono = { version = "0.4.42", features = ["serde"] }
diesel = { version = "2.3.3", features = ["sqlite"] }
diesel_migrations = "2.3.0"
anyhow = "1.0.100"
axum = { version = "0.8.7", features = ["macros"]}
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
thiserror = "2.0.17"
tower-http = { version = "0.6", features = ["cors"] }